# Generated by Django 4.1.3 on 2022-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="campanha", name="status",),
        migrations.AddField(
            model_name="campanha",
            name="finalizado",
            field=models.BooleanField(default=False),
        ),
    ]
