# Generated by Django 4.1.3 on 2022-11-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanha",
            name="descricao",
            field=models.TextField(default="nenhuma descrição", max_length=500),
            preserve_default=False,
        ),
    ]
