# Generated by Django 4.1.3 on 2022-11-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_campanha_descricao"),
        ("project", "0002_remove_campanha_status_campanha_finalizado"),
    ]

    operations = []
