# Generated by Django 4.1.3 on 2022-11-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_merge_20221112_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campanha",
            name="descricao",
            field=models.TextField(max_length=200),
        ),
    ]
