# Generated by Django 4.1.3 on 2022-11-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_campanha_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campanha",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
