# Generated by Django 4.1.3 on 2022-11-13 16:07

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_campanha_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="doacao",
            name="cc_code",
            field=creditcards.models.SecurityCodeField(
                default="", max_length=4, verbose_name="security code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="cc_expiry",
            field=creditcards.models.CardExpiryField(
                default="01/01", verbose_name="expiration date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="cc_number",
            field=creditcards.models.CardNumberField(
                default="", max_length=25, verbose_name="card number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="cpf_titular",
            field=models.CharField(default="", max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="email",
            field=models.EmailField(
                default="", max_length=254, verbose_name="email_address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doacao",
            name="nome_cartao",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
