# Generated by Django 4.1.3 on 2022-11-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_doacao_cc_code_doacao_cc_expiry_doacao_cc_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensagemFAQ",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email_address"),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=200)),
            ],
        ),
    ]
